server: 
    port: 7070 
spring:
    main:
        banner-mode: "off"
    jpa:
        database: h2 
        generate-ddl: true 
        show-sql: true 
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            ddl-auto: create-drop
logging:
    level:
        org:
            springframework: INFO 
